***Consider the below code to answer further questions:***<br>
import numpy as np<br>
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]<br>
array_list = np.array(object = list_)<br>

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4', '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
print("Data type of list_: ", type(list_))
print("Data type of array_list: ", array_list.dtype)

Data type of list_:  <class 'list'>
Data type of array_list:  <U1


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [6]:
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)<br>
## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [8]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4', '5' ]
array_list = np.array(object = list_, dtype = int)
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


***Consider the below code to answer further questions:***<br>
import numpy as np<br>
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]<br>
num_array = np.array(object = num_list)<br>

## Q4. Write a code to find the following characteristics of variable, num_array:
1. shape
2. size

In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
size = len(num_list)
shape = (len(num_list), len(num_list[0]))

In [20]:
size, shape

(2, (2, 3))

In [13]:
num_array.shape, num_array.size

((2, 3), 6)

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [21]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [22]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])